function Q = TuneQ(Qrx, Qry, Qrz, Qvx, Qvy, Qvz, Qqs, Qqx, Qqy, Qqz, Qwx, Qwy, Qwz)
    Q = diag([ ...
                (Qrx/1000)^2, ...                   % m 2 km
                (Qry/1000)^2, ...                   % m 2 km
                (Qrz/1000)^2, ...                   % m 2 km
                (Qvx/1000)^2, ...                   % m/s 2 km/s
                (Qvy/1000)^2, ...                   % m/s 2 km/s
                (Qvz/1000)^2, ...                   % m/s 2 km/s
                Qqs^2, ...
                Qqx^2, ...
                Qqy^2, ...
                Qqz^2, ...
                deg2rad(Qwx)^2, ...
                deg2rad(Qwy)^2, ...
                deg2rad(Qwz)^2, ...
    ]);
end