function Q = TuneQ(Qrx, Qry, Qrz, Qvx, Qvy, Qvz, Qqs, Qqx, Qqy, Qqz, Qwx, Qwy, Qwz, dt_f)



    Q = diag([ ...
                (Qrx/1000)^2, ...                   % m 2 km
                (Qry/1000)^2, ...                   % m 2 km
                (Qrz/1000)^2, ...                   % m 2 km
                (Qvx/1000)^2, ...                   % m/s 2 km/s
                (Qvy/1000)^2, ...                   % m/s 2 km/s
                (Qvz/1000)^2, ...                   % m/s 2 km/s
                (0.5*deg2rad(Qqs))^2, ...
                (0.5*deg2rad(Qqx))^2, ...
                (0.5*deg2rad(Qqy))^2, ...
                (0.5*deg2rad(Qqz))^2, ...
                deg2rad(Qwx)^2, ...
                deg2rad(Qwy)^2, ...
                deg2rad(Qwz)^2, ...
    ]) * dt_f;
end