function P = TuneP(Prx, Pry, Prz, Pvx, Pvy, Pvz, Pqs, Pqx, Pqy, Pqz, Pwx, Pwy, Pwz)
    P = diag([ ...
                (Prx/1000)^2, ...               % m 2 km
                (Pry/1000)^2, ...               % m 2 km
                (Prz/1000)^2, ...               % m 2 km
                (Pvx/1000)^2, ...               % m/s 2 km/s
                (Pvy/1000)^2, ...               % m/s 2 km/s
                (Pvz/1000)^2, ...               % m/s 2 km/s
                (0.5*deg2rad(Pqs))^2, ...
                (0.5*deg2rad(Pqx))^2, ...
                (0.5*deg2rad(Pqy))^2, ...
                (0.5*deg2rad(Pqz))^2, ...
                deg2rad(Pwx)^2, ...
                deg2rad(Pwy)^2, ...
                deg2rad(Pwz)^2, ...
    ]);
end